export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            height: "80px",
          }}
          className="header"
        >
          <h1>AuthRootLayout</h1>
        </header>
        <main
          style={{
            height: "calc(100vh - 265px)", // Adjust height to fill the remaining space
          }}
          className="main"
        >
          {children}
        </main>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            height: "80px",
          }}
          className="footer"
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
