import Link from "next/link.js";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MarketingRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header
        style={{
          backgroundColor: "lightblue",
          padding: "1rem",
          height: "100px",
        }}
        className="header"
      >
        <h1>Marketing Layout</h1>
        <Link href="/">Home</Link>
      </header>
      <main
        style={{
          minHeight: "calc(100vh - 180px)",
        }}
      >
        {children}
      </main>
      <footer
        style={{
          backgroundColor: "ghostwhite",
          padding: "1rem",
          height: "80px",
        }}
        className="footer"
      >
        <p>Footer</p>
      </footer>
    </>
  );
}
