import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";
import "../styles.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js",
    template: "%s | Next.js",
    absolute: "https://example.com",
  },
  description: "Generated by Next.js",
};

export default function MarketingRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{<ErrorWrapper>{children}</ErrorWrapper>}</body>
    </html>
  );
}
