export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MarketingRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header
        style={{
          backgroundColor: "lightblue",
          padding: "1rem",
          height: "80px",
        }}
        className="header"
      >
        <h1>MarketingRootLayout</h1>
      </header>
      <main
        style={{
          height: "calc(100vh - 265px)", // Adjust height to fill the remaining space
        }}
        className="main"
      >
        {children}
      </main>
      <footer
        style={{
          backgroundColor: "ghostwhite",
          padding: "1rem",
          height: "80px",
        }}
        className="footer"
      >
        <p>Footer</p>
      </footer>
    </>
  );
}
